### PR TITLE
Modify version number to be pep440 compatible

### PR DESCRIPTION
**Pull request by jrhoads**
This had caused an issue when creating a `Pipfile.lock` using `pipenv`

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
Looks good to me!

**Comment by jrhoads** [comment]
Thank you.  Rebased

**Comment by wetneb** [comment]
@jrhoads my understanding is that this does not need to be pushed to PyPI because it is not an official release, right?

**Comment by jrhoads** [comment]
Thank you for merging

That is correct as far as this PR is concerned.

To be honest, a PyPI release would be nice too at some point.  One of the primary reasons I started using the pre-release version was it included some fixes that were not yet present in the released version.

This PRs fix is the smallest/least change that got everything working.

**Comment by wetneb** [comment]
Done, version 2.5.1 is released.

**Pull request merged**
