### PR TITLE
Add py37 test envs to tox and travis configs.

### PR DESCRIPTION
**Pull request by somexpert**
Hey all, just wanted to see if we could include the Python 3.7 envs for tox and Travis. No code changes needed (that I know of), just want to show that the code supports Python 3.7 as-is (based on the tests).

### CODE REVIEW

**Comment by wetneb** [comment]
Looks good to me but it seems that Travis isn't actually configured to run on pull requests? That is curious.

**Comment by wetneb** [comment]
@jascoul could you look into enabling Travis for this repository? I do not seem to have the privileges to enable it.

**Comment by interrogator** [comment]
This is a good one, it should trigger once merged into master? Or from travis website you can select the branch to test? But yeah, trusted 3.7 support is important for my project, and I'm sure it's not just me!

**Comment by wetneb** [comment]
What I mean is that Travis's checks do not show up in this pull request as they normally should - so something in the GitHub-Travis integration must be broken for this repository.

**Comment by wetneb** [comment]
And looking at https://travis-ci.org/github/jascoul/pyoai/pull_requests, it seems that Travis does not actually run for pull requests.

It is hard to help with reviewing PRs without this. So, let me reiterate:

@jascoul could you look into enabling Travis for this repository? I do not seem to have the privileges to enable it.

**Comment by interrogator** [comment]
Three options I see:

a) workaround: maybe travis will run on tagged pushes? could be worth a try with some random tag name. also maybe it runs if branch name is master? idk
b) best practice: get travis configured to run on PRs or find out why it's not currently @jascoul 

if @jascoul is not available, then (c):

* run whatever tests travis does locally with 3.7 in there, using tox or whatever else
* get this merged, then it'll run anyway (master != "a release" so not end of world if master briefly fails test, i'm sure people install project via pypi mostly anyway)
* if there's a failure, the fix should be easy enough, not much difference 3.6 / 3.7
* make an actual release with bump2version + tags (perhaps including a few other incoming PRs and fixes that seem doable in the coming days...
* new (minor?) version on pypi

Sorry for spamming so much in the past days, but yeah I need to make a decision on using this lib *very* soon and whipping it into shape would make the decision way simpler.

**Comment by wetneb** [comment]
Closing this as I dropped Travis and configured GitHub Actions instead, with 3.7 in it.

**Pull request closed without merging**
