### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by tkurze**
Hi,

I changed a few imports and exception handling to achieve Python3 compatibility.
I tested quickly against a local library repository and encountered no problems. I didn't ran any further tests though.

### CODE REVIEW

**Comment by jascoul** [comment]
Hi Tobias,

Thanks, that's awesome, looks great.
 I'll try to run some tests this week and then merge and do a pypi release

**Comment by tkurze** [comment]
Hi Jasper,

no problem. Glad I could help :)

**Comment by jascoul** [comment]
Hi,

I just merged your patch. 
I changed the code a bit to remove the six dependency, and some other minor issues.
Can you test if this works for you on python3? 
I will do a pypi release soon.

**Comment by tkurze** [comment]
Hi,

OK. Cool. I'll test in the next few days.

**Pull request merged**
